import "./globals.css";
// import Script from "next/script";
import type { Metadata } from "next";
import Providers from "@/components/Providers";
import Header from "@/components/layout/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "ALPHA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="fr">
      <body className="selection:bg-blue-500  selection:text-white">
        <Providers>
          <Header />
          <main className="mt-[70px]">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
